//! A module for working with processes for the Glyim standard library.
//!
//! T011-PATCHED [STD-5]: the runtime FFI uses a *handle* (an opaque `usize`
//! generated by `glyim_process_spawn`'s out-parameter) rather than a pid,
//! and passes arguments via out-pointers. The previous .g code
//!   - declared `glyim_process_spawn` with 7 arguments returning an i32
//!     pid, but the runtime takes 5 arguments and writes the handle
//!     through the 5th (`out_handle: *mut usize`), so the caller's
//!     `stdin_cfg`/`stdout_cfg`/`stderr_cfg` integer values were being
//!     written into (arbitrary memory),
//!   - declared `glyim_process_wait(pid: u32) -> i32` but the runtime takes
//!     `(handle: usize, out_exit_code: *mut i32)`, so the exit code was
//!     written through a garbage pointer,
//!   - declared `glyim_process_wait_output` with 7 arguments vs the
//!     runtime's 6 (out-pointer allocation model),
//!   - declared `glyim_process_kill(pid) -> i32` vs the runtime's
//!     `(handle, signal)`.
//!
//! The corrected declarations below use the real out-parameter handle model.
//!
//! Known remaining gap (T011 follow-up, tracked but not closed): the runtime
//! `glyim_process_spawn` does not accept `env`, `current_dir`, or per-stream
//! `Stdio` configs yet, so `Command::env(...)`/`Command::current_dir(...)`
//! are recorded on the struct but not forwarded. `Command::output()`
//! additionally rebuilds the command from scratch — a data-loss bug that
//! will be fixed when the runtime grows that surface.

/// The `Command` struct for building up process execution configurations.
struct Command {
    program: String,
    args: Vec<String>,
    env: Vec<(String, String)>,
    current_dir: Option<String>,
    stdin: Stdio,
    stdout: Stdio,
    stderr: Stdio,
}

impl Command {
    /// Construct a new `Command` for launching the program at path `program`.
    fn new(program: &str) -> Command {
        Command {
            program: program.to_string(),
            args: Vec::new(),
            env: Vec::new(),
            current_dir: Option::None,
            stdin: Stdio::Inherit,
            stdout: Stdio::Inherit,
            stderr: Stdio::Inherit,
        }
    }

    /// Add an argument to pass to the program.
    fn arg(mut self, arg: &str) -> Command {
        self.args.push(arg.to_string());
        self
    }

    /// Add multiple arguments to pass to the program.
    fn args(mut self, args: &[&str]) -> Command {
        for arg in args {
            self.args.push(arg.to_string());
        }
        self
    }

    /// Insert or update an environment variable mapping.
    fn env(mut self, key: &str, value: &str) -> Command {
        self.env.push((key.to_string(), value.to_string()));
        self
    }

    /// Set the working directory for the child process.
    fn current_dir(mut self, dir: &str) -> Command {
        self.current_dir = Option::Some(dir.to_string());
        self
    }

    /// Set configuration for the child process's standard input.
    fn stdin(mut self, cfg: Stdio) -> Command {
        self.stdin = cfg;
        self
    }

    /// Set configuration for the child process's standard output.
    fn stdout(mut self, cfg: Stdio) -> Command {
        self.stdout = cfg;
        self
    }

    /// Set configuration for the child process's standard error.
    fn stderr(mut self, cfg: Stdio) -> Command {
        self.stderr = cfg;
        self
    }

    /// Execute the command as a child process, returning a handle to it.
    ///
    /// T011-PATCHED [STD-5]: use the runtime's real 5-argument,
    /// out-parameter signature. The handle is an opaque `usize` that the
    /// runtime assigns to the child in its process registry.
    fn spawn(self) -> Result<Child, String> {
        extern "C" {
            fn glyim_process_spawn(
                cmd: *const u8,
                cmd_len: usize,
                args: *const u8,
                args_len: usize,
                out_handle: *mut usize,
            ) -> i32;
        }
        let args_str = self.args.join("\0");
        let mut handle: usize = 0;
        let rc = unsafe {
            glyim_process_spawn(
                self.program.as_ptr(),
                self.program.len(),
                args_str.as_ptr(),
                args_str.len(),
                &mut handle,
            )
        };
        if rc != 0 || handle == 0 {
            Result::Err(format!("failed to spawn process: {}", self.program))
        } else {
            Result::Ok(Child {
                handle,
                stdin: Option::None,
                stdout: Option::None,
                stderr: Option::None,
            })
        }
    }

    /// Execute the command and wait for it to complete.
    fn status(self) -> Result<ExitStatus, String> {
        let child = self.spawn()?;
        child.wait()
    }

    /// Execute the command and collect its stdout.
    ///
    /// T011-FOLLOWUP-PATCHED [STD-5]: the previous version rebuilt a fresh
    /// `Command` from `self.program` + `self.args`, discarding `self.env`
    /// and `self.current_dir`. Now `output()` simply spawns `self` (the
    /// runtime's `glyim_process_spawn` already pipes stdout/stderr) and
    /// collects the output. Note: the runtime still doesn't forward
    /// `env`/`current_dir` to the child — that remains an open item
    /// tracked alongside T011.
    fn output(self) -> Result<Output, String> {
        let child = self.spawn()?;
        child.wait_with_output()
    }
}

/// A process spawned by a `Command`.
struct Child {
    handle: usize,
    stdin: Option<ChildStdin>,
    stdout: Option<ChildStdout>,
    stderr: Option<ChildStderr>,
}

impl Child {
    /// Wait for the child to exit and return its exit status.
    fn wait(self) -> Result<ExitStatus, String> {
        extern "C" {
            fn glyim_process_wait(handle: usize, out_exit_code: *mut i32) -> i32;
        }
        let mut code: i32 = -1;
        let rc = unsafe { glyim_process_wait(self.handle, &mut code) };
        if rc != 0 {
            Result::Err(format!("failed to wait for process {}", self.handle))
        } else {
            Result::Ok(ExitStatus { code })
        }
    }

    /// Simultaneously wait for the child to exit and collect all remaining output on stdout/stderr.
    fn wait_with_output(self) -> Result<Output, String> {
        extern "C" {
            fn glyim_process_wait_output(
                handle: usize,
                stdout_ptr: *mut *mut u8,
                stdout_len: *mut usize,
                stderr_ptr: *mut *mut u8,
                stderr_len: *mut usize,
                out_exit_code: *mut i32,
            ) -> i32;
            fn glyim_free_cstr(ptr: *mut u8);
        }
        let mut out_ptr: *mut u8 = ptr::null_mut();
        let mut out_len: usize = 0;
        let mut err_ptr: *mut u8 = ptr::null_mut();
        let mut err_len: usize = 0;
        let mut code: i32 = -1;
        let rc = unsafe {
            glyim_process_wait_output(
                self.handle,
                &mut out_ptr,
                &mut out_len,
                &mut err_ptr,
                &mut err_len,
                &mut code,
            )
        };
        if rc != 0 {
            return Result::Err(format!("failed to get output from process {}", self.handle));
        }
        let mut stdout_buf = Vec::new();
        if !out_ptr.is_null() && out_len > 0 {
            let s = unsafe { slice::from_raw_parts(out_ptr as *const u8, out_len) };
            stdout_buf.extend_from_slice(s);
            unsafe { glyim_free_cstr(out_ptr); }
        }
        let mut stderr_buf = Vec::new();
        if !err_ptr.is_null() && err_len > 0 {
            let s = unsafe { slice::from_raw_parts(err_ptr as *const u8, err_len) };
            stderr_buf.extend_from_slice(s);
            unsafe { glyim_free_cstr(err_ptr); }
        }
        Result::Ok(Output {
            status: ExitStatus { code },
            stdout: stdout_buf,
            stderr: stderr_buf,
        })
    }

    /// Return the process ID.
    fn id(&self) -> u32 {
        self.handle as u32
    }

    /// Forcefully kill the child process.
    fn kill(&self) -> Result<(), String> {
        extern "C" {
            fn glyim_process_kill(handle: usize, signal: i32) -> i32;
        }
        // Signal 15 = SIGTERM. The runtime maps this to a graceful
        // termination request.
        let rc = unsafe { glyim_process_kill(self.handle, 15) };
        if rc != 0 {
            Result::Err(format!("failed to kill process {}", self.handle))
        } else {
            Result::Ok(())
        }
    }
}

/// A handle to a child process's standard input.
struct ChildStdin {
    fd: i32,
}

/// A handle to a child process's standard output.
struct ChildStdout {
    fd: i32,
}

/// A handle to a child process's standard error.
struct ChildStderr {
    fd: i32,
}

/// Describes what to do with a standard I/O stream for a child process.
enum Stdio {
    /// Inherit the parent's standard I/O stream.
    Inherit,
    /// Use a pipe for the standard I/O stream.
    Piped,
    /// Redirect the standard I/O stream to /dev/null (or NUL on Windows).
    Null,
}

impl Stdio {
    fn to_raw(&self) -> u32 {
        match self {
            Stdio::Inherit => 0,
            Stdio::Piped => 1,
            Stdio::Null => 2,
        }
    }
}

/// The exit status of a process.
struct ExitStatus {
    code: i32,
}

impl ExitStatus {
    /// Was termination successful? Signal termination is not considered a success.
    fn success(&self) -> bool {
        self.code == 0
    }

    /// Return the exit code, if any.
    fn code(&self) -> Option<i32> {
        Option::Some(self.code)
    }
}

/// The output of a finished process.
struct Output {
    status: ExitStatus,
    stdout: Vec<u8>,
    stderr: Vec<u8>,
}

impl Output {
    /// Return the exit status.
    fn status(&self) -> &ExitStatus {
        &self.status
    }

    /// Return the stdout as bytes.
    fn stdout(&self) -> &[u8] {
        &self.stdout
    }

    /// Return the stderr as bytes.
    fn stderr(&self) -> &[u8] {
        &self.stderr
    }
}

/// Terminate the current process with the specified exit code.
fn exit(code: i32) -> ! {
    extern "C" {
        fn glyim_process_exit(code: i32) -> !;
    }
    unsafe { glyim_process_exit(code) }
}

/// Get the ID of the current process.
fn id() -> u32 {
    extern "C" {
        fn glyim_process_getpid() -> u32;
    }
    unsafe { glyim_process_getpid() }
}

/// Get the ID of the parent process.
fn parent_id() -> u32 {
    extern "C" {
        fn glyim_process_getppid() -> u32;
    }
    unsafe { glyim_process_getppid() }
}

/// Abort the process abnormally.
fn abort() -> ! {
    extern "C" {
        fn glyim_process_abort() -> !;
    }
    unsafe { glyim_process_abort() }
}
