[package]
name = "glyim-runtime"
edition.workspace = true
version.workspace = true

[profile.dev]
opt-level = 0
debug = false

[dependencies]
socket2 = "0.5"
libc = "0.2"
mio = { version = "1", features = ["net", "os-poll"] }
glyim-core = { workspace = true }
tracing = { workspace = true }
windows-sys = { version = "0.59", features = [
    "Win32_System_Console",
    "Win32_System_Threading",
    "Win32_Foundation",
    "Win32_System_Diagnostics_ToolHelp",
] }

[dev-dependencies]
libc = "0.2"
