use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Lockfile {
    #[serde(rename = "package")]
    pub packages: Vec<LockedPackage>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    pub hash: String,
    #[serde(default)]
    pub is_macro: bool,
    pub source: LockSource,
    #[serde(default)]
    pub deps: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "type")]
pub enum LockSource {
    #[serde(rename = "registry")]
    Registry { url: String },
    #[serde(rename = "path")]
    Path { path: String },
    #[serde(rename = "local")]
    Local,
}

/// Generate a lockfile from resolved dependencies.
pub fn generate_lockfile(
    resolved: &HashMap<String, (String, String, bool, Vec<String>, LockSource)>,
) -> Lockfile {
    let mut packages: Vec<LockedPackage> = resolved
        .iter()
        .map(|(name, (version, hash, is_macro, deps, source))| {
            let mut deps = deps.clone();
            deps.sort();
            LockedPackage {
                name: name.clone(),
                version: version.clone(),
                hash: hash.clone(),
                is_macro: *is_macro,
                source: source.clone(),
                deps,
            }
        })
        .collect();
    packages.sort_by(|a, b| a.name.cmp(&b.name));
    Lockfile { packages }
}

/// Parse a lockfile from TOML string.
pub fn parse_lockfile(toml_str: &str) -> Result<Lockfile, crate::PkgError> {
    let lockfile: Lockfile = toml::from_str(toml_str).map_err(|e| {
        crate::PkgError::Lockfile(format!("invalid lockfile TOML: {e}"))
    })?;
    Ok(lockfile)
}

/// Serialize a lockfile to TOML string with header comment.
pub fn serialize_lockfile(lockfile: &Lockfile) -> String {
    let mut out = String::from(
        "# This file is @generated by glyim-pkg.\n# Do not edit manually.\n\n",
    );
    out.push_str(&toml::to_string_pretty(lockfile).unwrap_or_default());
    out
}

/// Compute a simple hash of byte content using SHA-256.
pub fn compute_content_hash(content: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let result = Sha256::digest(content);
    hex::encode(result)
}
